apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: online-inference-v3
  labels:
    app: online-inference-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-inference-v3
  template:
    metadata:
      name: online-inference-v3
      labels:
        app: online-inference-v3
    spec:
      containers:
        - image: alexandertikh/online_inference:v4
          name: online-inference-v3
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /status
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 3